sahlberg/libiscsi

utils/Makefile.am, utils/iscsi-perf.c
this adds the very first version of iscsi-perf to measure throughput
to and performance of an iscsi LUN.
=> util: introduce iscsi-perf

lib/discovery.c
=> discovery: set cmdsn in discovery pdu

include/iscsi-private.h, include/iscsi.h, lib/connect.c, lib/discovery.c, lib/init.c, lib/iscsi-command.c, lib/libiscsi.def, lib/libiscsi.syms, lib/nop.c, lib/pdu.c, lib/socket.c, lib/sync.c, utils/iscsi-perf.c
Hi Ronnie,
please have a look. Still heavy testing required.
Peter
=> Reconnect async

lib/pdu.c
=> pdu: add known exceptions to target serial processing

test-tool/test_reserve6_target_cold_reset.c
Signed-off-by: Vadim Finkelstein <vadim@pi-coral.com>
=> test_reserve6_target_cold_reset: fix login parameters

lib/connect.c, lib/pdu.c
=> reconnect: copy scsi_timeout on reconnect

lib/Makefile.am, utils/iscsi-ls.c
Hi Ronnie, please take a look. Thanks!
=> Fix iscsi-ls for IPv6 link-local addresses, and bump ABI version again

include/iscsi-private.h, lib/connect.c, lib/discovery.c, lib/init.c, lib/iscsi-command.c, lib/login.c, lib/nop.c, lib/pdu.c, lib/task_mgmt.c
Hi Ronnie,
do you remember why data out PDUs have the callback of the cmd_pdu copied into their struct?
Peter
=> Fix seg fault on reconnect/timeout

.gitignore
=> gitignore: really ignore autom4te.cache

test-tool/test_extendedcopy_descr_limits.c
ExtendedCopy.DescrLimits currently attempts to test Maximum Descriptor
List Length bounds checking by issuing a request with
(max_target_desc_count + 1 + max_segment_desc_count + 1) descriptors.
Maximum Descriptor List Length is a separately advertised field, that
may not be exceeded with the above logic, e.g. LIO advertises:
- Max Target Desc Count = 2
- Max Segment Desc Count = 1
- Max Desc List Len = 1024
Calculate the number of descriptors using the advertised Maximum
Descriptor List Length value, to explicitly test bounds checking.
=> TESTS: exceed Maximum Descriptor List Length

test-tool/test_extendedcopy_validate_tgt_descr.c
With SPC-4, the 0xE4 descriptor LU ID TYPE field should be ignored, and
the NUL bit is obsolete. Update the ValidTgtDescr accordingly.
=> TESTS: fix ExtendedCopy.ValidTgtDescr for SPC-4

examples/iscsi-dd.c
Signed-off-by: Andrei Vagin <avagin@openvz.org>
=> examples/iscsi-dd: parse the -x option

lib/connect.c
Minor cosmetic fixes around lib/connect.c, specifically iscsi_reconnect().
=> Reconnect fixes

lib/init.c
I would like to get some comments on this approach. I can't really test WIN32, so not sure what's the best practice here. Also, I didn't run into any bugs here, just fixing the code based on not being entirely happy with the last fixes (that I wrote...).
=> Call srand() only once

lib/connect.c, test-tool/iscsi-test-cu.c, test-tool/test_prin_read_keys_truncate.c
This pull request includes three fixes for bugs I ran into while testing iSCSI target implementations.
=> Three bug fixes for the libiscsi test tool

test-tool/test_multipathio_simple.c
This makes the data consistency check slightly more useful.
=> test_multipathio_simple: change data with path

examples/iscsi-dd.c
iscsi-dd is quite useful for comparing XCOPY offloaded and regular READ/WRITE copy performance. This patchset makes iscsi-dd a little more user friendly for this use-case.
=> examples/iscsi-dd: add usage and performance output

examples/iscsi-dd.c
=> examples/iscsi-dd: check for clock_gettime() errors

include/iser-private.h, lib/iser.c
Implement an allocator for allocating memory region of different lengths.
The allocator registers 4MB memory chunks as memory regions, and select a
free segment from one of them each time.
4KB is the minimum allocation unit, and free segments in the same chunk can be
merged into a larger free segment by the rule of buddy allocation. As a result,
size of allocated segments will be power of 2, this may waste some space but
produces less fragments.
In each chunk, a complete binary tree (which is actully an array) is used
to maintain free segments. Each node records the order of the largest segment
can be allocated from its subtree. Here's a miniature example.
A chunk with all segments free:
level 4                         4(0x1)
level 3            3(0x2)                      3(0x3)
level 2 …
=> iser: dynamic memory region allocator

lib/socket.c
Cmdsn of a data-out pdu struct is less than `expcmdsn` since it's from its
cmd pdu. A data-out pdu doesn't carray a cmdsn on the wire actually, so it
doesn't matter to itself, but if we rewrite the cmdsn of a immediate pdu with
it, it will cause an error.
Related error logs:
libiscsi: iscsi_write_to_socket: outqueue[0]->cmdsn < expcmdsn (3648bab5 < 3648bab9) opcode 00 [iqn.2003-01.org.linux-iscsi.tgt0]
libiscsi: reconnect initiated [iqn.2003-01.org.linux-iscsi.tgt0]
libiscsi: connecting to portal 127.0.0.1 [iqn.2003-01.org.linux-iscsi.tgt0]
libiscsi: connection established (127.0.0.1:62404 -> 127.0.0.1) [iqn.2003-01.org.linux-iscsi.tgt0]
Signed-off-by: wanghonghao <wanghonghao@bytedance.com>
=> socket: fix rewrite cmdsn of immediate pdus

Makefile.am, packaging/RPM/libiscsi.spec.in
Signed-off-by: Thanos Makatos <thanos.makatos@nutanix.com>
=> assorted RPM fixes

examples/iscsi-dd.c
=> Iscsi-dd cleanup

include/iser-private.h, lib/iser.c
Fix segmentation fault when using ISER. See commit message for details.
=> Fix iser sigsegv v2

examples/iscsi-dd.c
Minor changes to output text in iscsi-dd
=> Examples various fixes

Makefile.am, packaging/RPM/libiscsi.spec.in
Hi, I got some problems when making rpm based on the current master branch, hope the following changes would help.
=> Added some necessary files into the dist tarball for rpm making

.gitignore
add libiscsi.syms to .gitignore
=> add libiscsi.syms to .gitignore

utils/iscsi-ls.c
If invalid option is input with iscsi-ls，such as "iscsi-ls -a iscsi://", the command just stuck here and do not print useful information for the user to correct.
Fix this problem with getopt_long.
=> fix iscsi-ls parameter parse

test-tool/test_iscsi_chap.c
Signed-off-by: Li kunyu <kunyu@nfschina.com>
=> test-tool: remove a redundant semicolon

lib/pdu.c
Signed-off-by: Li kunyu <kunyu@nfschina.com>
=> pdu: Remove temporary variables from functions

.gitignore, utils/iscsi-perf.c
Misc fixes, see commits in this PR.
=> Misc fixes

.gitignore, utils/Makefile.am, utils/iscsi-discard.c
=> Iscsi discard

.gitignore, utils/Makefile.am, utils/iscsi-md5sum.c
=> Iscsi md5sum

utils/iscsi-discard.c
The blocks may exceed the block limits offered by the target, query unmap/write zero max blocks by inquiry
SCSI_INQUIRY_PAGECODE_BLOCK_LIMITS command, than use a loop to do the job.
=> iscsi-discard: adapt block limits

lib/logging.c, lib/socket.c
+ include LUN into log messages
+ restore logging of local ip and port
+ log resolved ip addresses if portal is a hostname
=> Add some logging improvements

include/iscsi-private.h, lib/socket.c
Data-Out PDUs should not increment ExpStatSN
=> fix ExpStatSN handling for Data-Out PDUs
