- lib/socket.c
since they are not used anywhere else.
set_tcp_sockopt in particular conflicts with libnfs's function of the same
name and prevents a a program from statically linking against both libnfs and
libiscsi.
Similar fix should also go into libnfs.
> set_tcp_* functions should be static 

- include/iscsi-private.h
- lib/init.c
- lib/iscsi-command.c
the recent implementation allows to send
iscsi->first_burst_length + iscsi->target_max_recv_data_segment_length
bytes if immediate and unsolicited data-out is send and
iscsi->target_max_recv_data_segment_length < iscsi->first_burst_length.
RFC3720 defines the length as:
Length=(min(FirstBurstLength, Expected Data
Transfer Length) - Received Immediate Data Length).
so that immediate data and unsolicited data-out are together
FirstBurstLength at maximum.
> iscsi-command: fix unsolicited data-out length

- configure.ac
- test-tool/test_preventallow_cold_reset.c
- test-tool/test_preventallow_lun_reset.c
- test-tool/test_preventallow_warm_reset.c
- utils/Makefile.am
- utils/iscsi-perf.c
When trying to compile libiscsi on OS X 10.9 I hit a few clang warnings and the new iscsi-perf makes use of clock_gettime which doesn't existing on OS X (see http://nadeausoftware.com/articles/2012/03/c_c_tip_how_measure_cpu_time_benchmarking#Discussion and http://stackoverflow.com/questions/5167269/clock-gettime-alternative-in-mac-os-x ). These patches fix these up (and tidy up some spacing in the util/Makefile.am while I'm there).
Looking at the fio source (https://github.com/axboe/fio/blob/1f440ece6127d2d274b961b6af0aa9091787702a/engines/posixaio.c#L36 ) shows that project uses gettimeofday when clock_gettime is unavailable so I do something similar here with autoconf (-lrt is always added to LIBS if we have clock_gettime) and ifdef headers. gettimeofday is bad because it's not …
> Iscsi perf clang

- .gitignore
- aros/iscsi-ls.c
- examples/iscsi-dd.c
- examples/ld_iscsi.c
- test-tool/iscsi-support.c
- utils/iscsi-perf.c
Only the 2nd patch is relevant for the bug fix, but of course all three patches may be pulled.
The first patch removes trailing blanks and was needed before further code modifications because my editor removes those blanks by default.
The 3rd patch was added to get a clean git status.
Regards
Stefan
> Fix wrong checks for username

- lib/init.c
observed when iscsi_destroy_context is called while a iscsi NOP out is in flight.
> init: fix segfault in iscsi_destroy_context

- aros/iscsi-ls.c
- examples/iscsi-dd.c
- examples/ld_iscsi.c
- include/iscsi.h
- lib/connect.c
- lib/init.c
- lib/nop.c
- lib/socket.c
- utils/iscsi-inq.c
- utils/iscsi-ls.c
- utils/iscsi-perf.c
- utils/iscsi-readcapacity16.c
- utils/iscsi-swp.c
We allowed iscsi to be NULL in iscsi_parse_url. Especially
qemu does this and currently segfaults at start. Change the
usage guidelines for target username/password to be the same
as for chap username/password.
This means the current users of target username/password
must be changed to retrieve the target credentials from
iscsi_parse_url and then set it via iscsi_set_target_username_pwd.
> init: fix segfaul in iscsi_parse_url

- lib/pdu.c
the lun parameter was missing.
> pdu: fix Target NOP-In debug output

- .gitignore
- examples/Makefile.am
- lib/Makefile.am
- test-tool/Makefile.am
- test-tool/iscsi-support.c
- test-tool/test_unmap_0blocks.c
- test-tool/test_writesame10_0blocks.c
- test-tool/test_writesame10_unmap_until_end.c
- test-tool/test_writesame16_0blocks.c
- test-tool/test_writesame16_unmap_until_end.c
- utils/Makefile.am
This patchset fixes writesame and unmap tests for targets that have WSNZ bit enabled by skipping the affected tests (printing a proper message) including a couple of other fixes where the number of blocks passed to writesame and unmap was incorrect. It also fixes 'out-of-tree' builds and adds two generated files to .gitignore.
> Fix '0block' write same and unmap tests and 'out-of-tree' builds

- test-tool/test_report_supported_opcodes_one_command.c
* SCSI_REPORT_SUPPORTING_OPCODE
* SCSI_REPORT_SUPPORTING_SERVICEACTION
> Skip unsupported tests instead of failing

- test-tool/Makefile.am
- test-tool/iscsi-multipath.c
- test-tool/iscsi-multipath.h
- test-tool/iscsi-test-cu.c
- test-tool/iscsi-test-cu.h
- test-tool/test_multipathio_simple.c
- Add support to iscsi-test-cu for multiple iscsi:// URLs. When multiple are provided, connect to each and check that they correspond to the same logical unit.
- Add a simple multipath IO test that checks for consistent data across multiple paths.
Changes since v1:
- Add tests_multipathio entry to all_suites and scsi_suites.
> test: multipath support v2

- test-tool/iscsi-support.c
- test-tool/test_modesense6_control_swp.c
Signed-off-by: Vadim Finkelstein <vadim@pi-coral.com>
> test_modesense6_control_swp: skip test if target cannot change swp

- autogen.sh
I noticed that if autoconf isn't installed, autogen.sh printed a confusing combination of an error message and instructions to continue, and exited successfully even though it had failed:
```
$ ./autogen.sh 
./autogen.sh: 7: ./autogen.sh: autoreconf: not found
Now run ./configure and then make.
$ echo $?
0
```
This small change to the autogen.sh script allows it to check that the commands it needs are available, and if necessary to report which commands are missing, and exit unsuccessfully.
> Allow for autogen.sh failure

- test-tool/Makefile.am
- test-tool/iscsi-multipath.c
- test-tool/iscsi-multipath.h
- test-tool/iscsi-support.c
- test-tool/iscsi-support.h
- test-tool/iscsi-test-cu.c
- test-tool/iscsi-test-cu.h
- test-tool/test_multipathio_compareandwrite.c
- test-tool/test_multipathio_reset.c
- test-tool/test_prout_clear_simple.c
Follow up to https://github.com/sahlberg/libiscsi/pull/170
- check for and clear any UAs before and after LU RESET
- ensure LU RESET test is only run on iSCSI transports
- Add multipath compare and write test
- add a Persistent Reservation Out CLEAR test
> Mp reset v2

- test-tool/iscsi-multipath.c
- test-tool/iscsi-multipath.h
- test-tool/test_preventallow_2_itnexuses.c
- test-tool/test_prout_reserve_access.c
- test-tool/test_prout_reserve_ownership.c
- test-tool/test_reserve6_2initiators.c
- test-tool/test_reserve6_itnexus_loss.c
- test-tool/test_reserve6_logout.c
- test-tool/test_reserve6_target_cold_reset.c
- test-tool/test_reserve6_target_warm_reset.c
- test-tool/test_sanitize_readonly.c
- test-tool/test_sanitize_reservations.c
<pre>
test-tool/iscsi-multipath.c                 |  57 +++++++++++
test-tool/iscsi-multipath.h                 |   4 +
test-tool/test_preventallow_2_itnexuses.c   |  19 ++--
test-tool/test_prout_reserve_access.c       | 104 +++++++-------------
test-tool/test_prout_reserve_ownership.c    | 104 +++++++-------------
test-tool/test_reserve6_2initiators.c       |  31 +++---
test-tool/test_reserve6_itnexus_loss.c      |  23 ++---
test-tool/test_reserve6_logout.c            |  23 ++---
test-tool/test_reserve6_target_cold_reset.c |  21 ++--
test-tool/test_reserve6_target_warm_reset.c |  22 ++---
test-tool/test_sanitize_readonly.c          |  19 ++--
test-tool/test_sanitize_reservations.c      |  17 ++--
12 files changed, 195 insertions(+), 249 deletions(-)
</pre>
> use multipath for secondary sessions (if available) instead of reconnecting

- test-tool/test_prout_preempt.c
Remove duplicate k2 deregistration.
Reported-by: Chris Zankel <czankel@purestorage.com>
> test/pr: fix key deregistration in PRout PREEMPT test

- lib/socket.c
- utils/iscsi-perf.c
Trying to compile libiscsi was broken on OS X because of the use of the Linux only `MSG_NOSIGNAL` so I've introduced a workaround. The workaround isn't perfect as you get pre-`MSG_NOSIGNAL` behaviour on OSes that don't have `MSG_NOSIGNAL` or `SO_NOSIGPIPE` but the alternative was to mess about with signal handlers (as described on http://stackoverflow.com/questions/2205455/detecting-broken-pipe-in-solaris-send-call ). While in socket.c I simplified the `SOL_TCP` check too.
Next up are a bunch of iscsi-perf fixes to complete the intent from 7c6a3e4 and the addition literal suffixes to fix the weird output (gigantic elapsed times) and behaviour (time limited tests resetting the remaining time part way through) I was seeing using iscsi-perf on a 32 bit Linux system.
PS: The email address …
> Socket and iscsi-perf fixes

- test-tool/Makefile.am
- test-tool/iscsi-test-cu.c
- test-tool/iscsi-test-cu.h
- test-tool/test_async_read.c
- test-tool/test_async_write.c
- test-tool/test_multipathio_async_caw.c
Dispatch a number of READ10 requests simultaneously, and await all
responses.
The iscsi-support test helper functions are currently all synchronous,
so this test mostly uses the bare libiscsi API. As new async tests are
added, we can make a more informed decision on which boilerplate code
can be split out.
> Tests: Asynchronous iSCSI

- include/iscsi-private.h
- lib/connect.c
- lib/login.c
Hi Ronnie,
I found Qemu segfaulting on storage timeouts with recent libiscsi. The reason you can find in the commits. I think we should invoke all callbacks of PDUs we drop, shouldn't we?
Peter
> Fix Qemu Segfault

- test-tool/test_async_abort_simple.c
- test-tool/test_async_read.c
- test-tool/test_async_write.c
- test-tool/test_multipathio_async_caw.c
When libiscsi is built with clang several spurious
missing-field-initializers warnings like the following are reported:
test_async_write.c:61:45: error: missing field 'completed' initializer
[-Werror,-Wmissing-field-initializers]
struct tests_async_write_state state = { 0 };
These appear to be due to clang being overzealous in its checking
because the code is legal C (see
https://llvm.org/bugs/show_bug.cgi?id=21689 ) but it causes compilation
to be aborted. Workaround the problem by specifying a 0 or NULL for each
structure member.
> Silence clang missing-field-initializers warning

- test-tool/iscsi-test-cu.c
Tests such as ProutPreempt presume each path they have is sending a
different initiator name. When using multipath this did not happen and
initiatorname1 was used on all paths.
Fix this by creating and initializing an array (currently size 2) of
initiator names and iterating it in step with each new path we make
(hopefully the compiler will complain if iscsi-test-cu ever supports
more than two multipaths and there isn't a corresponding initiatorname).
Signed-off-by: Sitsofe Wheeler <sitsofe@yahoo.com>
> Tests: Ensure each path sends a different initiator when using multipath

- test-tool/iscsi-test-cu.c
Make it easier for build systems to tell a test run had failures by
changing the exit code to 1.
Signed-off-by: Sitsofe Wheeler <sitsofe@yahoo.com>
> Tests: Exit iscsi-test-cu with 1 if a test fails

- test-tool/Makefile.am
- test-tool/iscsi-test-cu.c
- test-tool/iscsi-test-cu.h
- test-tool/test_writesame10_check.c
- test-tool/test_writesame16_check.c
Based on the corresponding simple tests. Issue a WRITESAME request and
confirm that the data written matches the data read back.
> tests: add WRITESAME data verification tests

- test-tool/iscsi-support.h
- test-tool/test_writesame10_0blocks.c
- test-tool/test_writesame16_0blocks.c
The current WRITE SAME (WS) 0 blocks test at LBA 0 isn't always correct
because if:
- The target's WSNZ bit set is 0
- The target's MAXIMUM WRITE SAME LENGTH (MWSL) is greater than 0
- We are issuing a WS with a NUMBER OF LOGICAL BLOCKS of 0
then whether the command should return success or failure depends on
whether the starting LBA is within MWSL blocks of the end of the LUN
(see http://www.t10.org/pipermail/t10/2016-May/017988.html for details).
Replace the vestigial code which tried to handle this (but no longer
worked since commit 8585e4509b72c9d1e8f814d67d53847a75c6a535 ) and add
some additional MAXIMUM WRITE SAME LENGTH tests.
Signed-off-by: Sitsofe Wheeler <sitsofe@yahoo.com>
CC'ing @ddiss, @bvanassche .
> Tests: WRITESAME 0-blocks fixes and improvements

- lib/libiscsi.def
- lib/libiscsi.syms
Remove iscsi_queue_pdu from the list of symbols otherwise clang on OSX
fails to compile with the following error:
Undefined symbols for architecture x86_64:
"_iscsi_queue_pdu", referenced from:
-exported_symbol[s_list] command line option
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
> lib: Remove unused iscsi_queue_pdu symbol

- README
cyrus-imapd project, where the README links to, has migrated their repo to github per: https://cgit.cyrus.foundation/cyrus-imapd/tree/README.TXT and the old link throws a 404:
```bash
$ curl -sv https://cgit.cyrus.foundation/cyrus-imapd/plain/cunit/cunit-to-junit.pl 2>&1 | grep 'HTTP/1.1'
> GET /cyrus-imapd/plain/cunit/cunit-to-junit.pl HTTP/1.1
< HTTP/1.1 404 Not found
```
Updated the README with new [URL](https://raw.githubusercontent.com/cyrusimap/cyrus-imapd/master/cunit/cunit-to-junit.pl), and fix a small typo
> Update a URL in README, fix a typo there too

- lib/iser.c
@shterman told they are unnecessary because this can't happen.
> iser: remove unnecessary checks for NULL

- test-tool/iscsi-test-cu.c
When run against an iSCSI target sd->sgio_dev may be NULL, so the
strncmp() coredumps.
Fixes: 698ae7a649e66a44f398cd35c9ac2118f7411487
> TESTS: drop /dev/sg device path check for iSCSI

- test-tool/Makefile.am
- test-tool/iscsi-test-cu.c
- test-tool/iscsi-test-cu.h
- test-tool/test_async_lu_reset_simple.c
Dispatch a write and subsequently reset the logical unit via iSCSI TMF.
This is based on the AbortTaskSimpleAsync test.
> TESTS: simple LU RESET TMF test

- examples/Makefile.am
- lib/Makefile.am
- tests/Makefile.am
- utils/Makefile.am
Signed-off-by: Vicente Olivert Riera Vincent.Riera@imgtec.com
> Do not use -I/usr/include. This is unsafe when cross-compiling.

- examples/iscsi-dd.c
- include/iscsi.h
- lib/iscsi-command.c
- lib/libiscsi.def
- lib/libiscsi.syms
- lib/sync.c
EXTENDED COPY can be triggered with the new --xcopy/-x parameter. When
invoked, (--max) EXTENDED COPY requests are dispatched in parallel, with
each request attempting to copy (--blocks) from source to destination.
Submitting for early feedback - I should probably split out the populate_X helpers into a library that can be shared with the test-tool code, as currently a lot of this is duplicate.
> examples/dd: add XCOPY support

- include/iscsi-private.h
- lib/crc32c.c
- lib/init.c
- lib/login.c
- lib/pdu.c
- lib/socket.c
@sahlberg as discussed
@shterman as far as i read the iser code it does not support header checksums. we should abort then if the target requests HeaderDigest=CRC32C
> fix crc32c header checksums and some bugs

- include/iscsi-private.h
- lib/connect.c
- lib/init.c
- lib/socket.c
iscsi_read_from_socket can currently only read one PDU in each iscsi_service invocation even
if there is more data available on the socket. This patch reads all PDUs until the socket
would block. It enqueues all complete read PDUs and then processes them in order of arrival.
> Batch pdu read in function iscsi_read_from_socket()

- utils/iscsi-perf.c
If with int defintion, this statement:
num_blocks = client->num_blocks - client->pos;
May not get the exact value we want.
Signed-off-by: optimistyzy <optimistyzy@gmail.com>
> iscsi-perf: fix overflow issue in fill_read_queue

- lib/sync.c
all sync commands that return an integer value are
supposed to return a negative value on error.
However, state.status is positive non-zero on error.
Fix this by returning -1 if the state.status is
not SCSI_STATUS_GOOD.
Reported-by: Sitsofe Wheeler <sitsofe@yahoo.com>
> sync: fix return value for various sync commands

- test-tool/test_nomedia_sbc.c
- test-tool/test_readonly_sbc.c
- test-tool/test_writeverify10_beyond_eol.c
- test-tool/test_writeverify10_dpo.c
- test-tool/test_writeverify10_residuals.c
- test-tool/test_writeverify10_simple.c
- test-tool/test_writeverify10_wrprotect.c
- test-tool/test_writeverify12_beyond_eol.c
- test-tool/test_writeverify12_dpo.c
- test-tool/test_writeverify12_simple.c
- test-tool/test_writeverify12_wrprotect.c
- test-tool/test_writeverify16_beyond_eol.c
- test-tool/test_writeverify16_dpo.c
- test-tool/test_writeverify16_residuals.c
- test-tool/test_writeverify16_simple.c
From SBC-4: BYTCHK = 0 means that the Data-Out buffer contents
must not be used. BYTCHK = 1 means that the Data-Out buffer must
be compared against the data on the storage medium. Hence set
BYTCHK to 1 if EDTL != 0.
Signed-off-by: Bart Van Assche <bart.vanassche@sandisk.com>
> test tool: Set BYTCHK=1 if EDTL != 0

- include/iscsi-private.h
- lib/connect.c
- lib/init.c
- lib/iscsi-command.c
- lib/pdu.c
- lib/sync.c
These address a segfault which may happen if the event_poll() return early (eg. timeout) for sync connect calls. On those cases, it is possible for a context to have PDUs queued which point to a local stack which have returned.
> PDU cancellation fixes for sync connect calls

- test-tool/test_writesame10_unmap_until_end.c
- test-tool/test_writesame16_unmap_until_end.c
2e947cc1de78d681c95c8be617724e26679a1dae added logic to check that
targets missing zero block writesame support return INVALID_FIELD_IN_CDB
to such requests. However, this change incorrectly set the writesame
number_of_logical_blocks field to one.
> test_writesame_unmap_until_end: fix unsupported fallback

- include/iscsi-private.h
- include/iscsi.h
In our use of libiscsi at Datto, we have come across several issues related to the automatic reconnect logic (mainly its interaction with `POLLHUP`). This allows us to disable the functionality, at the expense of writing our own reconnect logic.
Related: #241
> Make iscsi_set_noautoreconnect public

- configure.ac
- lib/iser.c
- lib/logging.c
- lib/scsi-lowlevel.c
- lib/sync.c
This fixes various memory leaks reported by Coverity, as well as new warnings in GCC 8 (sometimes by disabling them...).
> Fix warnings from Coverity and GCC 8

- Makefile.am
- configure.ac
In some cases, tests, tool and eexamples are not needed, especially
in a production system, when everything has been pre-validated.
Add three new config options, each to disable parts of the build:
- tests
- test-tool
- examples
Additionally, make the cunit detection really a cache-val, using the 
canonical autoconf machinery.
> buildsys: add options to disable part of the build, fix cunit detection

- test-tool/iscsi-test-cu.c
clear_pr() can be called before connect_scsi_device() has been invoked
on each MPIO sdev. This results in a NULL pointer dereference in the
send_scsi_command() MPIO NOP-responder code-path.
Fix this by invoking clear_pr() after the MPIO connect_scsi_device()
loop has run. clear_pr() also only needs to be invoked via a single
path, so do so via the first path only.
Link: https://github.com/sahlberg/libiscsi/issues/289
Fixes: 16435a9 ("iscsi-test-cu: Improve persistent reservation clearing")
> test-tool: fix MPIO clear_pr() behaviour

- lib/iser.c
- lib/login.c
Added support for negotiating below keys:
RDMAExtensions, TargetRecvDataSegmentLength, and
InitiatorRecvDataSegmentLength.
These are required to support iSER. See RFC5046 Section 6.
> Added support for iSER related iSCSI keys

- lib/discovery.c
rfc3720 indicates that SendTargets on discovery *and* normal operational
sessions must be supported by targets:
A system that contains targets MUST support discovery sessions on
each of its iSCSI IP address-port pairs, and MUST support the
SendTargets command on the discovery session.
...
A target MUST support the SendTargets command on operational
sessions...
> discovery: permit SendTargets on normal sessions

- test-tool/iscsi-support.c
- test-tool/iscsi-support.h
- test-tool/iscsi-test-cu.c
- test-tool/test_compareandwrite_invalid_dataout_size.c
- test-tool/test_iscsi_cmdsn_toohigh.c
- test-tool/test_iscsi_cmdsn_toolow.c
- test-tool/test_iscsi_datasn_invalid.c
- test-tool/test_sanitize_block_erase_reserved.c
- test-tool/test_sanitize_crypto_erase_reserved.c
- test-tool/test_sanitize_overwrite_reserved.c
test-tool/iscsi-support.c includes it's own iscsi_queue_pdu() function, which can be used by tests for intercepting PDU dispatch and falling through to the libiscsi path via dlsym() lookup.
With https://github.com/sahlberg/libiscsi/issues/297 we want to allow the test tool to directly use low-level libiscsi functions, which is complicated by the duplicate iscsi_queue_pdu() symbol.
The iSCSI context already includes a transport-specific queue_pdu() callback, so use that for overloading instead.
> test-tool: rework iscsi_queue_pdu() overloading

- lib/Makefile.am
- test-tool/Makefile.am
- test-tool/test_iscsi_cmdsn_toohigh.c
- test-tool/test_iscsi_cmdsn_toolow.c
- test-tool/test_iscsi_datasn_invalid.c
As a follow up to https://github.com/sahlberg/libiscsi/pull/299 , this patchset sees iscsi-test-cu statically link against a new libiscsipriv library, which allows tests to now make full use of internal libiscsi functionality for PDU mainipulation etc.
Only a single test has been changed to use the newly available symbols, but further tests for SendTargets and Nop-Out will follow.
> test-tool: add and link against libiscsipriv convenience library

- lib/iser.c
Discovered this while running iSCSI.iSCSITMF AbortTaskSimpleAsync
test case. For Task Management command iser_pdu->iscsi_pdu.scsi_cbdata
is not set. When test case tries to send Task Management command
via common API iser_send_command() - it calls overflow_data_size
which tries to dereference scsi_cbdata leading to SEGFAULT.
Added a non-NULL check for scsi_cbdata before accessing it.
Link: https://github.com/sahlberg/libiscsi/issues/293
> lib/iser.c: fix overflow_data_size NULL ptr dereference

- configure.ac
- test-tool/iscsi-support.c
- test-tool/test_async_abort_simple.c
- test-tool/test_async_lu_reset_simple.c
- test-tool/test_async_write.c
- test-tool/test_compareandwrite_unwritten.c
- test-tool/test_multipathio_async_caw.c
- test-tool/test_writesame10_check.c
- test-tool/test_writesame16_check.c
Since it is easy to trigger a stack overflow with variable-length arrays,
use dynamic memory allocation instead of VLAs. Add -Wvla to the compiler
options such that no new VLAs get introduced.
Signed-off-by: Bart Van Assche <bvanassche@acm.org>
> Use dynamic memory allocation instead of variable-length arrays

- lib/login.c
In logic.c, data segment parameters in the text segment are converted to
signed longs.  Changing from strtol -> strtoul fixes compiler errors on
certain platforms that warn against comparing a signed long with
uint32_t using MIN.
> Fix data segment length comparison to unsigned long

- test-tool/iscsi-support.h
Without this, linking fails on Fedora rawhide. Example:
...
/usr/bin/ld: test_async_lu_reset_simple.o:/root/libiscsi/libiscsi.git/test-tool/iscsi-support.h:59: multiple definition of `param_list_len_err_ascqs'; iscsi-test-cu.o:/root/libiscsi/libiscsi.git/test-tool/iscsi-support.h:59: first defined here
/usr/bin/ld: test_async_lu_reset_simple.o:/root/libiscsi/libiscsi.git/test-tool/iscsi-support.h:58: multiple definition of `invalid_cdb_ascqs'; iscsi-test-cu.o:/root/libiscsi/libiscsi.git/test-tool/iscsi-support.h:58: first defined here
...
> test-tool: Use 'extern int' for declaring global variables in headers

- lib/login.c
The prior condition could be summarized as:
```
if ((first && second) || second) {
```
This will always evaluate to `second`:
```
((true && true) || true) == true
((false && true) || true) == true
((true && false) || false) == false
((false && false) || false) == false
```
> Simplify the logic that determines when to send headers

- test-tool/iscsi-test-cu.c
- test-tool/iscsi-test-cu.h
- test-tool/test_compareandwrite_invalid_dataout_size.c
- test-tool/test_iscsi_chap.c
- test-tool/test_iscsi_cmdsn_toohigh.c
- test-tool/test_iscsi_cmdsn_toolow.c
- test-tool/test_iscsi_datasn_invalid.c
- test-tool/test_sanitize_block_erase_reserved.c
- test-tool/test_sanitize_crypto_erase_reserved.c
- test-tool/test_sanitize_overwrite_reserved.c
In my tests I hit a stack overflow caused by infinite recursion of
.queue_pdu() calls, caused by .queue_pdu() not being restored in an
error path. Make the approach for restoring .queue_pdu() more robust.
Signed-off-by: Bart Van Assche <bvanassche@acm.org>
> Improve robustness of the code that restores .queue_pdu()

- lib/connect.c
- lib/init.c
- lib/iser.c
- lib/socket.c
Fix several bugs for iser, include memory leak, uncanceled thread, re-connect logic.
And test a lot about these patches, use software gateway to emulate bad/good network.
All of these patches work fine.
Test env:
```
192.168.122.204: run as a software gateway
192.168.122.205: run iser target, default gateway 192.168.122.204
192.168.122.206: run QEMU as intiator, default gateway 192.168.122.204
```
run script on 192.168.122.204:
```
for i in `seq 1 100`
do
iptables -s 192.168.122.205/32 -A FORWARD -m statistic --mode random --probability 1 -j DROP
iptables -s 192.168.122.206/32 -A FORWARD -m statistic --mode random --probability 1 -j DROP
sleep 30
iptables -F
sleep 30
done
```
> Fix several bugs for iser

- test-tool/test_writesame10_unmap_until_end.c
- test-tool/test_writesame16_unmap_until_end.c
If "number of blocks" is 0, write_same will not erase the LBA range and
read-verify will fail.
> specify number of blocks in write_same command

- configure.ac
- include/iscsi-private.h
- lib/init.c
- lib/iser.c
Since 2c1619edef61a03cb516efaa81750784c3071d10 for linux kernel and
55843c4ab8f559679d28c559cc4d681836be769b for rdma-core, rdma cma
supports RDMA_OPTION_ID_ACK_TIMEOUT. It's useful for RDMA out of
sequence case. Because this feature is added recently, we have to
check this in autogen.sh before building source code.
In production enviroument, the latency between two adapters is usually
less than 100us, so 1ms ack timeout is enough to avoid retransmission
flood.
Test under different packet loss rate and different ack timeout, run
fio (iodepth=1) in a guest os, I got this result:
latency under packet loss rate 0.00001:
timeout 19: avg 170.22, pct99.9 215
timeout 10: avg 160.08, pct99.9 215
timeout 8 : avg 146.39, pct99.9 177
timeout 7 : avg 148.37, pct99.9 211
latency under packet loss rate …
> iser: support rdma ack timeout optimization

- test-tool/iscsi-support.c
- test-tool/iscsi-support.h
These changes are preparation for adding test support for 0x0A type XCOPY segment descriptors.
> test/xcopy: minor clean up and refactoring

- test-tool/iscsi-support.c
This commit fixes some tests (like ProutReserve) on pure 4k devices.
> test-tool: Use block_size instead of hardcoded 512 bytes

- lib/iscsi-command.c
- lib/nop.c
- lib/pdu.c
- lib/socket.c
This patchset fixes some bugs on cancellation handling. The first patch tries to plug the cmdsn gap when the pdus are cancelled before sending out. The second one remove a check to enable cancellation during login. The last two patches make the cancellation handling work during reconnecting.
> Fix cancellation handling

- utils/iscsi-ls.c
Libiscsi supports to parse two iscsi url schemes: 'iscsi://' and 'iser://'.
Fix the missing iser parsing, introduced from 12222077.
Signed-off-by: Han Han <hhan@redhat.com>
> iscsi-ls: Fix iser url scheme parsing

- lib/pdu.c
Fixes: 10868c4 ("libiscsi: Avoid discontinuities in cmdsn ordering in some cases")
> pdu: fix use after free during cancellation

- test-tool/iscsi-test-cu.c
- test-tool/iscsi-test-cu.h
- test-tool/test_async_write.c
This PR includes a use-after-free fix already submitted separately via https://github.com/sahlberg/libiscsi/pull/338 . I've added the new test to the tests_iscsi_tmf group which is probably wrong, but wanted to avoid yet another group.
> test-tool: add LogoutDuringIOAsync

- test-tool/test_iscsi_cmdsn_toohigh.c
- test-tool/test_iscsi_cmdsn_toolow.c
After commit 10868c491d1d16fe2879fdba30a95d855fa936a6 CmdSN tests no
longer work because iscsi->cmdsn is incremented during the second test
phase (sending "good" TUR after "bad" TUR), so the resulting CmdSN is
not ExpCmdSN, but ExpCmdSN + 1 that is not acknowledged by the target.
This commit fixes the issue by setting iscsi->cmdsn to iscsi->expcmdsn - 1.
Affected tests:
* iSCSI.iSCSIcmdsn.iSCSICmdSnTooLow
* iSCSI.iSCSIcmdsn.iSCSICmdSnTooHigh
> test-tool: Fix CmdSN tests

- test-tool/iscsi-test-cu.c
If device claims SBC-3 version in its version descriptors it won't be marked as SBC-3 compliant.
This commit adds checks for:
* SBC-3 T10/BSR INCITS 514 revision 35
* SBC-3 T10/BSR INCITS 514 revision 36
* SBC-3 ANSI INCITS 514-2014
> test-tool: add version descriptor checks for more SBC-3 versions

- lib/init.c
Otherwise:
```
In file included from init.c:42:
init.c: In function 'iscsi_create_context':
init.c:296:20: error: format '%lu' expects argument of type 'long unsigned int', but argument 4 has type 'size
296 |  ISCSI_LOG(iscsi,5,"small allocation size is %lu byte", iscsi->smalloc_size);
|                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~  ~~~~~~~~~~~~~~~~~~~
|                                                              |
|                                                              size_t {aka unsigned int}
./../include/iscsi-private.h:357:36: note: in definition of macro 'ISCSI_LOG'
357 |    iscsi_log_message(iscsi, level, format, ## __VA_ARGS__); \
|                                    ^~~~~~
init.c:296:48: note: format string is defined here
296 |  ISCSI_LOG(iscsi,5,"small …
```
> init: fix Wformat on 32-bit platforms

- test-tool/Makefile.am
- test-tool/iscsi-test-cu.c
- test-tool/iscsi-test-cu.h
- test-tool/test_report_luns.c
Check for duplicate LUN entries in the REPORT LUNS response.
> test-tool: add simple REPORT LUNS test

- test-tool/iscsi-test-cu.c
- test-tool/iscsi-test-cu.h
- test-tool/test_report_luns.c
SPC-3 6.21 REPORT LUNS command states:
Device servers compliant with SPC return CHECK CONDITION status, with
the sense key set to ILLEGAL REQUEST, and the additional sense code
set to INVALID FIELD IN CDB when the allocation length is less than
16 bytes.
Test this requirement by sending REPORT LUNS requests with ALLOCATION
LENGTH values under, equal to and over 16 bytes.
> test-tool: test various ALLOC LENGTHS for REPORT LUNS

- include/iscsi-private.h
- test-tool/Makefile.am
- test-tool/test_write10_residuals.c
- test-tool/test_write12_residuals.c
- test-tool/test_write16_residuals.c
- test-tool/test_write_residuals.c
- test-tool/test_write_residuals.h
Linux target implementation, TCM, doesn’t pass write residuals tests (Write10Residuals, Write12Residualds, Write16Residuals).
One of the reason why they fail is because TCM doesn’t complete writes that have residuals with GOOD status, instead it replies with CHECK CONDITION and INVALID FIELD IN CDB sense code. The sense code doesn’t seem to be a valid reply but it's legit for a target to reply with CHECK CONDITION as outlined in [the discussion on T10](https://www.t10.org/pipermail/t10/2012-September/016350.html), RFC 7143 (11.4.5.1.  Field Semantics): 
```
Targets may set the residual count, and initiators may use
it when the response code is Command Completed at Target (even if the
status returned is not GOOD)
```
and FCP-4 (9.4.2 FCP_DATA IUs for read and write operations):
```
If the …
```
> Improve WriteResidual tests

- utils/iscsi-ls.c
Otherwise:
```
../../libiscsi-1.19.0/utils/iscsi-ls.c:181:6: error: implicitly declaring library function 'strncasecmp' with type 'int (const char *, const char *, unsigned long)' [-Werror,-Wimplicit-function-declaration]
if (strncasecmp(portal, "[fe80:", 6) == 0) {
^
../../libiscsi-1.19.0/utils/iscsi-ls.c:181:6: note: include the header <strings.h> or explicitly provide a declaration for 'strncasecmp'
1 error generated.
*** [iscsi-ls.o] Error code 1
```
> Add header <strings.h> for strncasecmp

- Makefile.am
- examples/Makefile.am
- lib/Makefile.am
- test-tool/Makefile.am
- tests/Makefile.am
- utils/Makefile.am
These are some improvements for the `Makefile.am` files.
1. When linking dependencies for the whole `Makefile.am` the variable is `LIBS`, not `LDADD`. This removes `LDADD` and replaces it with `LIBS` as needed.
2. When linking dependencies the correct variable is `libfoo_LIBADD` for libraries and `foo_LDADD` for programs while `LDFLAGS` should only be used for other linker flags such as `-no-undefined` or `-version-info`.
3.  This adds `-no-undefined` where applicable to help detect the undefined references fixed in the first commit. Please note that GNU libtool has a long standing design where `-no-undefined` is silently ignored and will not be respected. However when using slibtool (https://dev.midipix.org/cross/slibtool) this will not be a problem and `-no-undefined` works as expected.
> Makefile.am improvements.

- include/scsi-lowlevel.h
- lib/scsi-lowlevel.c
- test-tool/test_receive_copy_results_copy_status.c
If ReceiveCopyResults is not implemented then we should skip this test.
> Before running the SCSI.ReceiveCopyResults.CopyStatus test we should check that it is supported

- configure.ac
In one of recent commits the argument passed to m4_esyscmd()
macro was switched to its unescaped version. This is not correct
because package version is then defined as "Version 1.19.0"
instead of just "1.19.0".
Fixes: cb4489776b2659d4ea8771d3ac7ba9323f34d863
Signed-off-by: Michal Privoznik <mprivozn@redhat.com>
> configure.ac: Quote argument to m4_esyscmd() properly

- test-tool/test_extendedcopy_simple.c
CU_PASS() needs to be coupled with a return to actually skip the test.
Similarly, the CU_PASS message isn't printed, so a logging() call is
also needed here.
> test: fix ExtendedCopy.Large SKIPPED cases

- include/iscsi.h
- lib/connect.c
- lib/libiscsi.def
- lib/libiscsi.syms.in
- lib/sync.c
If a connection attempt is hung, then iscsi_reconnect() won't do anything. This
makes sense if we'd just re-try to connect to the same target, but if (for
example) login redirect might point us to a different, healthy, target, it
should be possible to restart the full connection process on request.
Signed-off-by: John Levon <john.levon@nutanix.com>
> add iscsi_force_reconnect()

- utils/Makefile.am
- utils/iscsi-pr.c
iscsi-pr uses libiscsi to connect target and issues PR command.
In most cases, iscsi-pr use the same parameters as sg_persist(from sg3-utils).
For example, use iscsi-pr to dump keys by command:
~# ./utils/iscsi-pr --read-keys iscsi://192.168.122.44/iqn.2003-01.org.linux-iscsi.bytedance.x8664:sn.a6b7bff3d509/0 -i iqn.2005-03.org.open-iscsi:12345678
PR generation=0x20, 19 registered reservation keys follow:
0xabcd1234
0xabcd
0xabcd
0xabc
A few command is not implemented in this patch, add them if necessary
in future.
Signed-off-by: zhenwei pi <pizhenwei@bytedance.com>
> iscsi-pr: add persistent reservation tool

- lib/iscsi-command.c
In iscsi_send_data_out() a PDU is allocated, but there is no error
handling logic to free it if the PDU cannot be queued.
iscsi_allocate_pdu() may allocate memory for the PDU. This memory may be
leaked if iscsi_queue_pdu() fails since there is no call to free it.
Orignally there was a free() call but it was removed as a part of a
cleanup adding checks for NULL pdu callbacks.
Fixes: 423b82efa4bd ("pdu: check callback for NULL everywhere")
Reviewed-by: Manish Mishra <manish.mishra@nutanix.com>
Signed-off-by: Raphael Norwitz <raphael.norwitz@nutanix.com>
> iscsi-command: Fix leak in iscsi_send_data_out

- lib/login.c
If a test sets the use_immediate_data parameter to ISCSI_IMMEDIATE_DATA_NO
for the iSCSI context, then the test expects that a data associated with
the Write command to be sent in a separate PDU.
But if for execute the command it is necessary to login on a target then
the use_immediate_data was previously set, will be rewrite during
the processing of the Login Response packet.
This happen during the iSCSI.iSCSIdatasn.iSCSIDataSnInvalid
(test_iscsi_datasn_invalid.c) test:
```
--> iSCSI 114 SCSI: Write(10) LUN: 0x01 (LBA: 0x00000064, Len: 1)
<-- iSCSI 114 Ready To Transfer
--> iSCSI 578 SCSI: Data Out LUN: 0x01 (Write(10) Request Data)
--> iSCSI 550 Login Command
Here we lose use_immediate_data value for iSCSI session.
<-- iSCSI 426 Login Response (Success)
--> iSCSI 114 SCSI: Test Unit …
```
> Fix to lose the immediate data param during login processing

- utils/iscsi-inq.c
According to the man page and help info, --debug=integer can specify the
debug_level, while it would report following error:
iscsi-inq --debug=2
iscsi-inq: option '--debug' doesn't allow an argument
It's because the iscsi-inq code did not handle this parameters
correctly. So here we just correct it.
Signed-off-by: Wenchao Hao <haowenchao@huawei.com>
> iscsi-inq: handle setting of debug_level correctly

- examples/iscsi-dd.c
- utils/iscsi-swp.c
add check after malloc to avoid referencing an illegal pointer
> add check after malloc to avoid referencing an illegal pointer and fix -d param

- lib/scsi-lowlevel.c
Check return value of scsi_malloc to avoid dereferencing NULL return value.
> fix dereferencing NULL return value

- lib/pdu.c
When execute iscsi_task_mgmt_lun_reset_async function,
pdus are already removed from waitpdu list. In iscsi_service
function, this will call iscsi_process_pdu and release
pdu from waitpdu again, which cause segmentation fault.
Whether waitpud list is NULL should be checked here to avoid
the problem.
Signed-off-by: geruijun <geruijun@huawei.com>
> Fix segmentation fault problem.

- aros/aros_compat.c
- lib/connect.c
Increase the check after malloc allocation, which should be helpful to the robustness of the program.
> aros_compat: Add check after malloc allocation

- lib/iser.c
The void type function basically does not need to write ` return； 'at the end of the statement block` Statement, which may look better
Signed-off-by: Li kunyu <kunyu@nfschina.com>
> iser: Remove unnecessary 'return;'

- include/iscsi-private.h
- include/iscsi.h
- lib/connect.c
- lib/init.c
- lib/iser.c
- lib/libiscsi.def
- lib/socket.c
libiscsi is widely used by poll driven, include libiscsi itself, QEMU. Using poll works fine after iscsi reconnect, but it does not work in epoll, because the epoll event has been removed during duplicating file descriptor in kernel.
Add a new function iscsi_set_fd_dup_cb to set callback, then uplayer gets notified after duplicating. The following codes reproduce this issue, and test this patch by compiling flags -DISCSI_FD_DUP_CB.
static void iscsi_epoll_event(struct iscsi_context *iscsi, int epollfd, bool new) {
static int epoll_event;
struct epoll_event ev = { 0 };
int pevent = iscsi_which_events(iscsi);
int event = 0;
if (pevent & POLLIN)
event |= EPOLLIN;
if (pevent & POLLOUT)
event |= EPOLLOUT;
ev.events = event;
ev.data.fd = iscsi_get_fd(iscsi);
if (new)
epoll_ctl(epollfd, …
> Add iscsi_set_fd_dup_cb

- utils/iscsi-inq.c
- utils/iscsi-perf.c
- utils/iscsi-pr.c
- utils/iscsi-swp.c
HEX format is friendly to iSCSI utils, for example: ./iscsi-inq -e 0x1 -c 0xb1 iscsi://...
atoi supports decimal only, this example does not work. Use strtol(nptr, NULL, 0) to auto-detect format, then this works fine.
> utils: use strtol instead of atoi

- include/iscsi.h
- lib/iscsi-command.c
Libiscsi users need a way to check if a task is queued to send (not sent yet) before invoking functions such as iscsi_task_mgmt_abort_task_async. Otherwise, because task management requests are automatically treated as "immediate", a request to abort a task is sent before the task itself.
if (iscsi_scsi_is_task_in_outqueue(iscsi_, task_)) {
iscsi_scsi_cancel_task(iscsi_, task_);
} else {
iscsi_task_mgmt_abort_task_async(iscsi_, task_, AbortCb, context_);
}
> checking if task is in outqueue

- doc/Makefile.am
- doc/iscsi-md5sum.1
- doc/iscsi-md5sum.xml
Add document for utils/iscsi-md5sum.
> doc: Add iscsi-md5sum

- lib/socket.c
Once error occurs on socker read/write, libiscsi tries to reconnect silently. Add necessary log message for this case.
> Log necessary message on internal reconnect

- lib/pdu.c
Describe the reason again:
A WRITE16 command[w] handles R2T, and queues DATAOUT PDU m,x,y,z:
```
outqueue->DATAOUT[x]->DATAOUT[y]->DATAOUT[z]...
outqueue_current->DATAOUT[m]
waitqueue->WRITE16[w]...
```
1, Once x, y, z gets released in initiator side, the target still expects the remaining DATAOUT PDUs.
2, Once command w timeout and callback to uplayer, uplayers usually releases memory of
iscsi task(include memory referenced by iovec.iov_base). DATAOUT[m] would access
invalid memory iovce.iov_base.
So invoke WRITEx command callback until draining DATAOUT PDUs.
Co-developed-by: Rui Zhang <zhangrui.1203@bytedance.com>
> Drain DATAOUT PDU on timeout

- test-tool/iscsi-support.c
'ms->pages' was not checked for being NULL. This can happen when a target does not return any pages.
> Fix for https://github.com/sahlberg/libiscsi/issues/409

- test-tool/iscsi-support.c
Previously, 'task->status' was printed as decimal. In iscsi.h, the
values that are put into it are defined as hexadecimal. This is a bit confusing (grepping through the code for 251658241 did not result in anything while the hex variant f000001 resulted in SCSI_STATUS_ERROR).
> print task-status in hex

- packaging/RPM/libiscsi.spec.in
- test-tool/test_compareandwrite_miscompare.c
- test-tool/test_sanitize_block_erase.c
- test-tool/test_sanitize_reset.c
- utils/iscsi-perf.c
- utils/iscsi-pr.c
These changes are carried in debian for a long time, some since 2016. The last one (implicity) is new in 1.20.0.
> spelling fixes: eventhough, shoudl, asyncronous, maxium, implicity

- COPYING
Fixes: e6bcdf5fdb "drop the LD_PRELOAD tool"
> COPYING: stop mentioning ld_scsi

- configure.ac
- lib/Makefile.am
- lib/login.c
libgcrypt is a relatively large dependency that is used only for the sake of computing MD5 in the CHAP authentication protocol. Some distributions may want to disable it forcibly and rely on the embedded MD5 implementation.
On the other hand, other distributions may want to standardize on as few crypto libraries as possible, and to that end it makes sense to support libgnutls which has a superset of the libgcrypt functionality. So add support for that one as well.
> allow choosing between libgcrypt, gnutls or embedded MD5

- test-tool/iscsi-support.c
This patch adds a timestamp before each logged line. That could help correlating a logging to a network-trace. Because of offsets in time between the tracer and the test and the DUT, this does not always help.
> A possible 'fix' for issue #415

- README.md
- include/iscsi-private.h
- include/iscsi.h
- lib/connect.c
- lib/crc32c.c
- lib/init.c
- lib/libiscsi.def
- lib/libiscsi.syms.in
- lib/login.c
- lib/pdu.c
- lib/socket.c
This PR adds Data Digest support to `libiscsi`.
The bulk of the configuration follows the existing code for the very similar Header Digest.  The most notable difference is that Data Digest will default to `None` (rather than `None,CRC32C` as is the case for Header Digest).  This preserves exiting behavior and avoids the potentially costly Data Digest from being selected accidentally.
Since CRC32C calculations on the data may not be all computed in a single operation, components of the existing `crc32c` function (used for Header Digest) has also been decomposed into three further functions:
- `crc32c_init`
- `crc32c_chain`
- `crc32c_chain_done`
Furthermore, for the same reason we will need to "carry around" an interim digest so `calculated_data_digest` is added to both `struct iscsi_pdu` …
> Add support for Data Digest

- include/iscsi-private.h
- lib/pdu.c
- lib/task_mgmt.c
The existing implementation of iscsi_task_mgmt_lun_reset_async cancels all tasks in ready-to-send and wait-for-completion queues. If the ISCSI context has in-flight tasks for a different LUNs or tasks that are not LUN-specific (such as NOPIN, NOPOUT), those tasks are not supposed to be affected by the LUN reset.
Also, the tasks for the LUN being reset may have in-flight responses not affected by a concurrent LUN reset; they have to be handled accordingly.
This change cancels only the tasks for the LUN being reset if they are in the ready-to-send queue ('outqueue'). The tasks in the wait-for- completion queue should be cancelled on LUN reset completion. For example:
iscsi_task_mgmt_lun_reset_async(iscsi, lun, lun_reset_cb, ctxt);
....
....
void lun_reset_cb(struct iscsi_context * iscsi, …
> lun_reset cancelling lun tasks only

- README.md
See https://github.com/sahlberg/libiscsi/issues/423
> libcunit1-dev is required for iscsi-test-cu to be build

- include/iscsi.h
- lib/connect.c
- lib/libiscsi.def
- lib/libiscsi.syms.in
When an iSCSI connection enters the reconnection phase, the backoff time (next_reconnect) increases with reconnection retry_cnt. However, if the client detects that the target has recovered before reaching next_reconnect, calling `iscsi_reconnect/iscsi_force_reconnect` has no any effect, making fast reconnection impossible.
This patch introduces an interface to reset next_reconnect, so that the client can reset the backoff time upon detecting target recovery and achieve faster reconnection.
Resolves: https://github.com/sahlberg/libiscsi/issues/428
> feat: add iscsi_reset_next_reconnect interface

- lib/socket.c
On reconnect case, the iscsi_tcp_connect tries to reuse the fd number of old_iscsi. However, this fd could have been already closed in previous iscsi_tcp_disconnect if iscsi->fd == iscsi->old_iscsi->fd and the fd number might have been allocated to some other caller, in this case the fd reuse in iscsi_tcp_connect is not safe anymore.
Solve this by not closing the fd if iscsi and old_iscsi share the same fd on reconnect to "really" reserve this fd number.
> lib: reserve the fd on reconnect

- lib/sync.c
When iscsi->fd gets invalid, there is not point to keep stuck in the event loop, instead could give an accurate error about the invalid fd.
> lib: finish event_loop on invalid fd

- lib/sync.c
In iSCSI synchronous operations, a struct iscsi_sync_state variable (state) is allocated on the stack, and its address is assigned to pdu->scsi_cbdata.private_data. This address is eventually used in the PDU callback function.
However, if a reconnection occurs during a synchronous operation (e.g., read or write), but the connect function fails (iscsi->fd will be set to -1), the event_loop times out and exits. At this point, unprocessed PDUs remain. If the PDU callback function is triggered after the timeout (e.g., during iscsi_destroy_context), it may access the pdu->scsi_cbdata.private_data address, which no longer points to the original stack allocation. Writing to this invalid address in the callback corrupts the current stack structure, leading to process crash.
This patch addresses …
> fix: scan PDUs before exiting event_loop due to connect timedout

- include/iscsi-private.h
- lib/login.c
This pull request addresses two related issues in the CHAP authentication code:
1. **Explicitly zero-initialize `target_chap_c` in `iscsi_login_add_chap_response()`**
- Previously, the code relied on stack memory being zeroed, which is undefined behavior and could lead to unpredictable CHAP_C values.
- This fix ensures that the buffer is safely initialized using `{0}`.
2. **Increase `MAX_CHAP_R_SIZE` to 32**
- The previous value was insufficient to hold a full SHA-256 hash (32 bytes).
- This change allows proper support for CHAP algorithms that require longer responses, such as SHA-256.
> Fix CHAP response buffer zero-init and increase MAX_CHAP_R_SIZE to support SHA-256

- include/iscsi-private.h
- lib/login.c
In the function compute_chap_r_md5(), the chap_c parameter is expected to be a hex-encoded ASCII string (e.g., "0x1234abcd..."), which is parsed back into raw binary before being hashed into the CHAP\_R response.
However, the code that constructs CHAP_C was passing raw binary data (target_chap_c) directly into compute_chap_r_md5(), without converting it to the expected ASCII hex string format. This led to incorrect CHAP\_R generation and authentication failure.
✅ **Fix**: Before sending CHAP_C and computing CHAP_R, we now explicitly convert each byte of target_chap_c to a two-character hex string and store it in a new buffer (target_chap_c_hex), which is passed to compute_chap_r_md5().
---
During the comparison of the received CHAP\_R response:
```c
if (c != iscsi->target_chap_r[i]) { ... …
```
> Fix CHAP_C Encoding and CHAP_R Comparison in CHAP Authentication

- lib/socket.c
The code in iscsi_read_from_socket was incorrectly including the PDU padding bytes in the data-size check against initiator_max_recv_data_segment_length. According to iSCSI RFC (e.g., RFC 3720), the DataSegmentLength field excludes any padding used to align the PDU. Only the actual payload length (DataSegmentLength) should be compared to initiator_max_recv_data_segment_length.
> Fix length check to exclude padding when comparing against initiator

- utils/iscsi-inq.c
While printing device identification information format binary values as hex instead of ASCII characters.
> iscsi-inq: binary values in hex

- lib/scsi-lowlevel.c
Fixing a potential fall-through in switch in data unmarshal function for maintenance-in commands. The fall-through never happens for valid commands, but the build tools may complain about it.
> fall-through in maintenancein unmarshal switch

- examples/iscsi-dd.c
Only show time stats if clock_gettime(3) is available. It's actually possible to have clock_gettime(3) and not yet support CLOCK_MONOTONIC on legacy systems, however on macOS, they all arrived together in macOS 10.12.
Rather than add new configure checks for CLOCK_MONOTONIC, I opted to use the existing HAVE_CLOCK_GETTIME.
libiscsi 1.20.2 now builds on Mac OS X 10.4 with examples.
> examples/iscsi-dd.c: add HAVE_CLOCK_GETTIME guards

- lib/connect.c
other device types might not implement evpd page 0x80 or change their serial.
> fix: do only query unit serial for non-removable direct access devices

- lib/connect.c
iscsi-ls --show-luns connects to lun -1 for which iscsi inquiry fails on some storage.
> fix: only try to read unit serial if lun != -1
